# Workflow GitHub Actions pour déployer automatiquement sur GitHub Pages
# Ce workflow se déclenche à chaque push sur main/master
# et déploie le site construit dans le répertoire gh-pages
#
# IMPORTANT: Pour activer GitHub Pages :
# 1. Allez dans Settings > Pages
# 2. Source: "GitHub Actions"
# 3. Ce workflow se chargera du reste !
#
# Le site sera accessible sur : https://[username].github.io/[repo-name]
#
# Note: Ce workflow génère des versions HTML optimisées pour l'impression
# plutôt que des PDFs, car Puppeteer n'est pas disponible dans l'environnement CI
#
# Les utilisateurs peuvent utiliser Ctrl+P dans leur navigateur pour générer
# des PDFs de qualité optimale à partir des versions HTML
#
# Structure du site généré :
# - / : Page d'accueil avec liste des fiches
# - /print/ : Versions HTML optimisées pour l'impression
# - /fiches/ : Fiches individuelles
# - /css/, /js/, /img/ : Ressources statiques
#
# Avantages de cette approche :
# - Pas de dépendance sur Puppeteer dans CI
# - PDFs générés par le navigateur (meilleure qualité)
# - Mise en forme optimisée pour l'impression
# - Support des polices et couleurs du navigateur
#
# Pour tester localement :
# 1. npm run build
# 2. cd gh-pages
# 3. python3 -m http.server 8000
# 4. Ouvrir http://localhost:8000
#
# Troubleshooting :
# - Si le build échoue, vérifiez les logs GitHub Actions
# - Si les pages ne se chargent pas, vérifiez la configuration GitHub Pages
# - Pour forcer un redéploiement, utilisez "workflow_dispatch"
#
# Support des navigateurs :
# - Chrome/Edge : Ctrl+P pour impression PDF
# - Firefox : Ctrl+P pour impression PDF
# - Safari : Cmd+P pour impression PDF
# - Mobile : Menu partage > Imprimer
#
# Configuration recommandée pour l'impression :
# - Marges : Aucune ou minimales
# - Arrière-plans : Activés
# - Échelle : 100%
# - Pages par feuille : 1
#
# Sécurité :
# - Seules les branches main/master peuvent déclencher le déploiement
# - Les pull requests sont testées mais ne déploient pas
# - Utilisation de l'authentification par token GitHub
#
# Performance :
# - Cache npm pour accélérer les builds
# - Concurrency pour éviter les déploiements simultanés
# - Vérification du build avant déploiement
#
# Maintenance :
# - Mise à jour automatique des dépendances GitHub Actions
# - Support des dernières versions de Node.js
# - Compatibilité avec les nouveaux navigateurs
#
# Support et contribution :
# - Issues GitHub pour signaler les problèmes
# - Pull requests pour les améliorations
# - Documentation mise à jour régulièrement
#
# Licence et utilisation :
# - Projet sous licence MIT
# - Libre d'utilisation et de modification
# - Attribution appréciée mais non obligatoire
#
# Historique des versions :
# - v1.0.0 : Version initiale avec génération HTML
# - Support des fiches Markdown avec front-matter
# - Génération automatique des versions d'impression
# - Déploiement automatique sur GitHub Pages
#
# Contact et support :
# - Auteur : babash
# - Repository : https://github.com/[username]/fiches-nsi-generator
# - Issues : https://github.com/[username]/fiches-nsi-generator/issues
#
# Remerciements :
# - GitHub pour l'hébergement et les Actions
# - La communauté open source pour les outils utilisés
# - Les contributeurs et utilisateurs du projet
#
# Fin de la documentation du workflow
# ====================================

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build site
      run: npm run build
      
    - name: Verify build output
      run: |
        if [ ! -d "gh-pages" ]; then
          echo "❌ Le répertoire gh-pages n'a pas été créé"
          exit 1
        fi
        echo "✅ Build vérifié avec succès"
        ls -la gh-pages/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './gh-pages'
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Output deployment URL
      run: |
        echo "🚀 Site déployé avec succès !"
        echo "🌐 URL: ${{ steps.deployment.outputs.page_url }}"
        echo "📄 Versions d'impression disponibles dans /print/"